import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Navbar from "@/components/navigations/Navbar";
import ButtonPurple from "@/components/buttons/Buttons";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="space-y-[3em]">
        <Image src="/hero.svg" width={400} height={400} />
        <div className="space-y-[1em]">
          <h1 className="text-pt-dark text-4xl font-bold">
            Don't Just pay rent <br />
            <span className="text-pt-light">Earn Dividend</span>
            <span className="text-base text-p-purple"> $</span>
          </h1>
          <p>
            Kewaa Provides a fractional investment platform for investors in
            real-estate on the blockchain.
          </p>
          <ButtonPurple styleprops="w-[50%]">Go to Marketplace</ButtonPurple>
        </div>
      </section>
      <section>
        <div>
          <h2>How does it work?</h2>
          <p>
            Kewaa enables fractional investment of rental real estate properties
            by utilizing the blockchain. Using an implementation of re-fungible
            token standard. every property is tokenized and represented as an
            NFT which is extended into a specific amount of ERC 20 tokens. the
            ERC20 tokens are an extension of each NFT and represent fractional
            ownership. each investor earn dividend from the rent paid per
            property. You can now imagine the possibilities.
          </p>
        </div>
        <Image src="/hero2.svg" width={400} height={400} />
      </section>
      <section>
        <h2>Problems we solve</h2>
        <div>
          <div>
            <div>
              <p>Inclusivity</p>
              <div>Icon</div>
            </div>
            <article>
              We believe the blockchain can transform real-estate in Africa.
              Currently real estate is relatively illiquid as one can't readily
              convert it to cash or other assets. Kewaa can solve this!
            </article>
          </div>
        </div>
      </section>


      <section>
        <h2>Latest Collection</h2>
        <div>


          <div className="bg-w">

          </div>
        </div>
      </section>
    </>
  );
}
