import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import ButtonPurple, {
  ButtonBlack,
  ButtonWhite,
} from "@/components/buttons/Buttons";
import { IoIosInfinite } from "react-icons/io";
import HouseCard from "@/components/landingpage/HouseCard";
import Solutions from "@/components/landingpage/Solutions";
import FAQ from "@/components/landingpage/FAQ";
import Link from "next/link";
import Modal from "@/components/landingpage/Modal";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Kewee - Earn Dividend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/hero.svg" />
      </Head>

      <section className="space-y-[3em] md:space-y-0 md:flex flex-row-reverse  justify-between items-center">
        <Image
          width={400}
          height={400}
          src="/hero.svg"
          alt="hero image"
          className="w-full md:w-[40%] h-[400px] lg:w-[50%]  object-contain"
        />
        <div className="space-y-[1em] md:space-y-[1.5em] lg:space-y-[2em] md:w-[55%] lg:w-[60%]">
          <h1 className="text-pt-dark text-4xl md:text-5xl lg:text-7xl font-bold">
            Don't Just pay rent <br />
            <span className="text-pt-light">Earn Dividend</span>
            <span className="text-base text-p-purple"> $</span>
          </h1>
          <p className="lg:w-[60%] lg:text-xl">
            Kewaa Provides a fractional investment platform for investors in
            real-estate on the blockchain.
          </p>
          <ButtonPurple styleprops="w-[50%] md:w-[40%] lg:w-[25%]">
            Go to Marketplace
          </ButtonPurple>
        </div>
      </section>

      <div className="lg:w-[95%] mx-auto space-y-[4em] md:space-y-[6em] lg:space-y-[10em]">
        <section className="space-y-[3em] md:space-y-0 md:flex justify-between">
          <div className="space-y-[1em] md:w-[50%]">
            <h2 className="text-white text-2xl font-bold">How does it work?</h2>
            <p className="text-pt-dark">
              Kewaa enables fractional investment of rental real estate
              properties by utilizing the blockchain. Using an implementation of
              re-fungible token standard. every property is tokenized and
              represented as an NFT which is extended into a specific amount of
              ERC 20 tokens. the ERC20 tokens are an extension of each NFT and
              represent fractional ownership. each investor earn dividend from
              the rent paid per property. You can now imagine the possibilities.
            </p>
          </div>
          <Image
            width={400}
            height={400}
            alt="hero image"
            src="/hero2.svg"
            className="w-full md:w-[40%]"
          />
        </section>

        <section className="space-y-[3em]">
          <h2 className="text-white text-2xl font-bold">Problems we solve</h2>
          <div className="space-y-[2em] md:space-y-0 md:flex justify-between items-center">
            <Solutions />
            <Solutions />
            <Solutions />
          </div>
        </section>

        <section className="space-y-[3em]">
          <h2 className="text-white text-2xl font-bold">Latest Collection</h2>
          <div className="space-y-[4em] md:space-y-0 lg:bg-[#F4F6FE] md:flex justify-between items-start">
            <HouseCard />
            <HouseCard />
          </div>
          <div className="text-center">
            <ButtonBlack styleprops="w-[45%] md:w-[30%] lg:w-[20%]">
              <Link href="/marketplace"> Go to Marketplace</Link>
            </ButtonBlack>
          </div>
        </section>

        <section className="space-y-[3em]">
          <h2 className="text-white text-2xl font-bold">FAQ</h2>
          <div className="space-y-[1em]">
            <FAQ />
            <FAQ />
            <FAQ />
          </div>
        </section>
      </div>
    </>
  );
}
